[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 web_app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
FLASK_ENV = "production"
PYTHON_VERSION = "3.11.0"

[healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3

[resources]
memory = "512MB"
cpu = "0.5"

[networking]
allowedOrigins = ["*"]

[volumes]
# 临时文件存储
uploads = "/tmp/uploads"
outputs = "/tmp/outputs"